import { createRequire } from 'node:module';
import { mkdir, writeFile, readFile, access, rename, rm } from 'node:fs/promises';
import { constants } from 'node:fs';
import { resolve, join } from 'node:path';
import { homedir } from 'node:os';
import { createHash, randomUUID } from 'node:crypto';

const root = resolve(import.meta.dirname, '..');
const require = createRequire(resolve(root, 'package.json'));
const executable = `ccusage${process.platform === 'win32' ? '.exe' : ''}`;
const installed = require.resolve(`@ccusage/ccusage-${process.platform}-${process.arch}/bin/${executable}`);
// npm may unpack the native optional package without its executable bit.
// The copy below explicitly sets the executable mode, as ccusage's launcher does.
const contents = await readFile(installed);
const digest = createHash('sha256').update(contents).digest('hex');
// Paseo builds Git plugins in staging, then moves the checkout before compiling.
// A versioned, content-addressed cache keeps the executable path valid after that move.
const cache = resolve(process.env.PASEO_USAGE_CACHE_DIR || join(process.env.XDG_CACHE_HOME || join(homedir(), '.cache'), 'paseo-usage-glance'));
const directory = join(cache, digest);
const binary = join(directory, executable), config = join(directory, 'ccusage.config.json');
async function publish(path, data, mode) {
  const existing = await readFile(path).catch(error => { if (error.code !== 'ENOENT') throw error; return null; });
  if (existing?.equals(Buffer.from(data))) return;
  await mkdir(directory, { recursive: true, mode: 0o700 });
  const temporary = `${path}.${randomUUID()}.tmp`;
  try { await writeFile(temporary, data, { mode, flag: 'wx' }); await rename(temporary, path); }
  finally { await rm(temporary, { force: true }); }
}
await publish(binary, contents, 0o700);
await publish(config, '{}\n', 0o600);
await access(binary, constants.X_OK);
await mkdir(resolve(root, 'server'), { recursive: true });
// The Paseo server bundle runs from an eval factory, without a plugin __dirname.
// Resolve the cached native dependency at preparation time on the daemon host.
await writeFile(resolve(root, 'server/backend.generated.ts'), `// Generated by scripts/prepare.mjs on the installation host.\nexport const backend = ${JSON.stringify({ binary, config, version: '20.0.20' })} as const;\n`);
